// Local fallback data — mirrors the shape returned by /api/destinations and
// /api/tours so the UI never changes once a real CMS endpoint is wired up.

export const placeholderDestinations = [
  {
    id: 1,
    slug: 'switzerland',
    title: 'Switzerland',
    image_url:
      'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80',
    rating: 4.9,
    starting_price: '1,25,000',
    duration: '7 Days',
    country: 'Switzerland',
    description: 'Switzerland is a landlocked country known for its stunning Alpine scenery, pristine lakes, and charming villages. From the majestic Matterhorn to the serene Lake Geneva, it offers breathtaking landscapes year-round. The country is famous for its precision watches, delicious chocolates, and world-class skiing resorts.',
    best_time_to_visit: 'June to September for hiking and outdoor activities, December to March for skiing and winter sports',
    best_places: [
      {
        name: 'Zermatt',
        image_url: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80',
        description: 'Car-free village at the foot of the Matterhorn',
      },
      {
        name: 'Interlaken',
        image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=900&q=80',
        description: 'Adventure capital between Lake Brienz and Lake Thun',
      },
      {
        name: 'Lucerne',
        image_url: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=900&q=80',
        description: 'Medieval town with Chapel Bridge and Lion Monument',
      },
    ],
    things_to_do: [
      { name: 'Scenic Train Rides', description: 'Experience the Glacier Express and Bernina Express through stunning Alpine landscapes' },
      { name: 'Skiing & Snowboarding', description: 'World-class ski resorts like Zermatt, St. Moritz, and Verbier' },
      { name: 'Lake Cruises', description: 'Relaxing boat trips on Lake Geneva, Lake Lucerne, and Lake Como' },
    ],
    culture: 'Swiss culture is a blend of German, French, Italian, and Romansh influences. The country values precision, punctuality, and quality. Traditional festivals, yodeling, and alphorn music are part of the rich cultural heritage.',
    cuisine: 'Swiss cuisine features fondue, raclette, rösti, and chocolate. Local specialties vary by region - German-speaking areas favor hearty dishes, while French-influenced regions offer refined culinary experiences.',
  },
  {
    id: 2,
    slug: 'bali',
    title: 'Bali, Indonesia',
    image_url:
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80',
    rating: 4.8,
    starting_price: '68,000',
    duration: '6 Days',
    country: 'Indonesia',
    description: 'Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. The island is home to religious sites such as cliffside Uluwatu Temple. Also, the resort town of Ubud has a rainforest and the Sacred Monkey Forest.',
    best_time_to_visit: 'April to October (dry season) for best weather, though it\'s beautiful year-round',
    best_places: [
      {
        name: 'Ubud',
        image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80',
        description: 'Cultural heart with rice terraces and art markets',
      },
      {
        name: 'Seminyak',
        image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80',
        description: 'Trendy beach town with luxury resorts and nightlife',
      },
      {
        name: 'Uluwatu',
        image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80',
        description: 'Cliff-top temple with stunning sunset views',
      },
    ],
    things_to_do: [
      { name: 'Temple Visits', description: 'Explore ancient Hindu temples like Tanah Lot and Uluwatu' },
      { name: 'Rice Terrace Trekking', description: 'Walk through the famous Tegallalang rice terraces' },
      { name: 'Water Sports', description: 'Surfing, diving, and snorkeling in crystal clear waters' },
    ],
    culture: 'Balinese culture is deeply rooted in Hinduism, with daily offerings, temple ceremonies, and traditional dance performances. The island is known for its warm hospitality and spiritual atmosphere.',
    cuisine: 'Balinese cuisine features dishes like nasi goreng, satay, and babi guling. Fresh seafood, tropical fruits, and aromatic spices are staples of the local diet.',
  },
  {
    id: 3,
    slug: 'santorini',
    title: 'Santorini, Greece',
    image_url:
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80',
    rating: 4.9,
    starting_price: '1,45,000',
    duration: '8 Days',
    country: 'Greece',
    description: 'Santorini is one of the Cyclades islands in the Aegean Sea. It was devastated by a volcanic eruption in the 16th century BC, forever shaping its rugged landscape. The whitewashed, cubiform houses of its 2 principal towns, Fira and Oia, cling to cliffs above an underwater caldera.',
    best_time_to_visit: 'April to October for warm weather and clear skies, with September being ideal',
    best_places: [
      {
        name: 'Oia',
        image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80',
        description: 'Famous for stunning sunsets and blue-domed churches',
      },
      {
        name: 'Fira',
        image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80',
        description: 'Capital town with shops, restaurants, and caldera views',
      },
      {
        name: 'Red Beach',
        image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80',
        description: 'Unique beach with red volcanic sand and cliffs',
      },
    ],
    things_to_do: [
      { name: 'Sunset Watching', description: 'Watch world-famous sunsets from Oia castle' },
      { name: 'Wine Tasting', description: 'Visit local vineyards and taste Assyrtiko wine' },
      { name: 'Boat Tours', description: 'Explore the caldera and volcanic islands by boat' },
    ],
    culture: 'Santorini combines traditional Greek island culture with luxury tourism. The island preserves its Cycladic architecture while offering high-end dining and entertainment experiences.',
    cuisine: 'Santorini cuisine features fresh seafood, fava beans, cherry tomatoes, and local wines. Traditional dishes include moussaka, souvlaki, and fresh grilled fish.',
  },
  {
    id: 4,
    slug: 'dubai',
    title: 'Dubai, UAE',
    image_url:
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
    rating: 4.7,
    starting_price: '55,000',
    duration: '5 Days',
    country: 'United Arab Emirates',
    description: 'Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture and a lively nightlife scene. Burj Khalifa, the tallest building in the world, dominates the skyscraper-filled skyline.',
    best_time_to_visit: 'November to April for pleasant weather, avoiding the extreme summer heat',
    best_places: [
      {
        name: 'Burj Khalifa',
        image_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
        description: 'World\'s tallest building with observation decks',
      },
      {
        name: 'Dubai Mall',
        image_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
        description: 'Massive shopping complex with aquarium and ice rink',
      },
      {
        name: 'Palm Jumeirah',
        image_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
        description: 'Artificial island with luxury resorts and beaches',
      },
    ],
    things_to_do: [
      { name: 'Desert Safari', description: 'Experience dune bashing, camel rides, and BBQ dinners' },
      { name: 'Shopping', description: 'Explore luxury malls and traditional souks' },
      { name: 'Architecture Tours', description: 'Admire modern marvels like the Burj Al Arab' },
    ],
    culture: 'Dubai is a melting pot of cultures, with expatriates from around the world. While rooted in Islamic traditions, the city embraces modernity and international influences.',
    cuisine: 'Dubai offers diverse international cuisine alongside traditional Emirati dishes. Local specialties include machboos, harees, and luqaimat. The city is also known for its fine dining scene.',
  },
];

export const placeholderTours = [
  {
    id: 1,
    slug: 'swiss-alps-explorer',
    title: 'Swiss Alps Explorer',
    short_description: '7 days of Alpine magic - villages, lakes & peaks',
    image_url:
      'https://images.unsplash.com/photo-1530841377377-3ff06c0ca713?auto=format&fit=crop&w=900&q=80',
    tour_type: 'international',
    description: 'Experience the breathtaking beauty of the Swiss Alps with this comprehensive tour. Explore charming villages, pristine lakes, and majestic mountain peaks.',
    price: 150000,
    duration: '7 Days',
    best_time_to_visit: 'June to September for hiking, December to March for skiing',
    popular_places: [
      {
        name: 'Zermatt',
        location: 'Swiss Alps',
        image_url: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Interlaken',
        location: 'Bernese Oberland',
        image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Lucerne',
        location: 'Central Switzerland',
        image_url: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Zurich',
        description: 'Welcome to Switzerland! Transfer to your hotel in Zurich. Evening at leisure to explore the city.',
        activities: ['Airport Transfer', 'Hotel Check-in', 'City Orientation'],
      },
      {
        day: 2,
        title: 'Zurich to Lucerne',
        description: 'Travel to Lucerne by train. Visit Chapel Bridge and Lion Monument. Evening cruise on Lake Lucerne.',
        activities: ['Train Journey', 'Sightseeing', 'Lake Cruise'],
      },
      {
        day: 3,
        title: 'Mount Pilatus',
        description: 'Excursion to Mount Pilatus. Enjoy the world\'s steepest cogwheel railway and panoramic views.',
        activities: ['Cable Car Ride', 'Cogwheel Railway', 'Mountain Hiking'],
      },
      {
        day: 4,
        title: 'Lucerne to Interlaken',
        description: 'Train journey to Interlaken. Visit Lake Brienz and Lake Thun. Evening at leisure.',
        activities: ['Scenic Train Ride', 'Lake Exploration', 'Hotel Check-in'],
      },
      {
        day: 5,
        title: 'Jungfraujoch Excursion',
        description: 'Full day excursion to Jungfraujoch - Top of Europe. Visit the Ice Palace and Sphinx Observatory.',
        activities: ['Mountain Railway', 'Ice Palace', 'Sightseeing'],
      },
      {
        day: 6,
        title: 'Grindelwald and Zermatt',
        description: 'Travel to Grindelwald, then continue to Zermatt. View the iconic Matterhorn.',
        activities: ['Scenic Drive', 'Matterhorn View', 'Village Walk'],
      },
      {
        day: 7,
        title: 'Departure',
        description: 'Transfer to Zurich airport for your return flight with unforgettable memories.',
        activities: ['Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '6 nights accommodation in 4-star hotels',
      'Daily breakfast',
      'Swiss Travel Pass',
      'Jungfraujoch excursion',
      'Mount Pilatus excursion',
      'Professional English-speaking guide',
    ],
    excluded: [
      'International flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner',
      'Tips and gratuities',
    ],
  },
  {
    id: 2,
    slug: 'bali-island-escape',
    title: 'Bali Island Escape',
    short_description: 'Temples, beaches & rice terraces - 6 days paradise',
    image_url:
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=900&q=80',
    tour_type: 'international',
    description: 'Discover the magic of Bali - from ancient temples to pristine beaches, rice terraces to vibrant culture.',
    price: 68000,
    duration: '6 Days',
    best_time_to_visit: 'April to October (dry season)',
    popular_places: [
      {
        name: 'Ubud',
        location: 'Central Bali',
        image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Seminyak',
        location: 'South Bali',
        image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Uluwatu',
        location: 'Southern Bali',
        image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Bali',
        description: 'Arrive at Denpasar Airport. Transfer to your hotel in Seminyak. Evening at leisure.',
        activities: ['Airport Transfer', 'Hotel Check-in', 'Beach Walk'],
      },
      {
        day: 2,
        title: 'Ubud Cultural Tour',
        description: 'Visit Ubud Monkey Forest, Tegallalang Rice Terraces, and traditional art markets.',
        activities: ['Monkey Forest', 'Rice Terraces', 'Art Market'],
      },
      {
        day: 3,
        title: 'Temple Tour',
        description: 'Visit Tirta Empul Temple, Ulun Danu Beratan Temple, and Tanah Lot sunset.',
        activities: ['Temple Visits', 'Cultural Experience', 'Sunset View'],
      },
      {
        day: 4,
        title: 'Beach Day',
        description: 'Relax at Seminyak Beach. Optional water sports activities. Evening beach club dinner.',
        activities: ['Beach Relaxation', 'Water Sports', 'Beach Club'],
      },
      {
        day: 5,
        title: 'Uluwatu and Kecak Dance',
        description: 'Visit Uluwatu Temple and watch the famous Kecak fire dance at sunset.',
        activities: ['Temple Visit', 'Cultural Dance', 'Cliff Views'],
      },
      {
        day: 6,
        title: 'Departure',
        description: 'Morning at leisure. Transfer to airport for departure.',
        activities: ['Shopping', 'Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '5 nights accommodation',
      'Daily breakfast',
      'Private transfers',
      'English-speaking guide',
      'Temple entrance fees',
    ],
    excluded: [
      'International flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner',
      'Visa fees',
    ],
  },
  {
    id: 3,
    slug: 'kerala-backwaters',
    title: 'Kerala Backwaters',
    short_description: 'Serene backwaters, tea gardens & houseboat stay',
    image_url:
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80',
    tour_type: 'domestic',
    description: 'Experience God\'s Own Country with serene backwaters, lush tea gardens, and pristine beaches.',
    price: 45000,
    duration: '5 Days',
    best_time_to_visit: 'September to March',
    popular_places: [
      {
        name: 'Alleppey',
        location: 'Kerala',
        image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Munnar',
        location: 'Western Ghats',
        image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Kochi',
        location: 'Coastal Kerala',
        image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Kochi',
        description: 'Arrive at Kochi airport. Transfer to hotel. Evening visit to Fort Kochi.',
        activities: ['Airport Transfer', 'Fort Kochi Walk', 'Sunset View'],
      },
      {
        day: 2,
        title: 'Kochi to Munnar',
        description: 'Drive to Munnar. Visit Cheeyappara and Valara waterfalls en route.',
        activities: ['Scenic Drive', 'Waterfall Visit', 'Tea Gardens'],
      },
      {
        day: 3,
        title: 'Munnar Sightseeing',
        description: 'Visit Eravikulam National Park, Tea Museum, and Mattupetty Dam.',
        activities: ['National Park', 'Tea Museum', 'Dam Visit'],
      },
      {
        day: 4,
        title: 'Munnar to Alleppey',
        description: 'Drive to Alleppey. Board houseboat for overnight backwater cruise.',
        activities: ['Houseboat Cruise', 'Backwater Experience', 'Village Visit'],
      },
      {
        day: 5,
        title: 'Departure',
        description: 'Disembark houseboat. Transfer to Kochi airport for departure.',
        activities: ['Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '4 nights accommodation',
      'Houseboat stay with meals',
      'Private transfers',
      'Breakfast',
      'Sightseeing',
    ],
    excluded: [
      'Flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner (except houseboat)',
      'Tips',
    ],
  },
  {
    id: 4,
    slug: 'ladakh-road-trip',
    title: 'Ladakh Road Trip',
    short_description: 'High Himalayas, monasteries & pristine lakes',
    image_url:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlEHZmA4FcVvMANw8rJ53jCPKZxkDQ6vr15fktitk_tQ&s=10',
    
      tour_type: 'domestic',
    description: 'Adventure through the high Himalayas with stunning monasteries, high passes, and pristine lakes.',
    price: 55000,
    duration: '7 Days',
    best_time_to_visit: 'June to September',
    popular_places: [
      {
        name: 'Leh',
        location: 'Ladakh',
        image_url: 'https://images.unsplash.com/photo-1580289141527-e176e5a5b0a6?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Nubra Valley',
        location: 'North Ladakh',
        image_url: 'https://images.unsplash.com/photo-1580289141527-e176e5a5b0a6?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Pangong Lake',
        location: 'Eastern Ladakh',
        image_url: 'https://images.unsplash.com/photo-1580289141527-e176e5a5b0a6?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Leh',
        description: 'Arrive at Leh airport. Rest for acclimatization. Evening Leh market visit.',
        activities: ['Airport Transfer', 'Acclimatization', 'Market Visit'],
      },
      {
        day: 2,
        title: 'Leh Local Sightseeing',
        description: 'Visit Shanti Stupa, Leh Palace, and Thiksey Monastery.',
        activities: ['Monastery Visit', 'Palace Tour', 'Stupa Visit'],
      },
      {
        day: 3,
        title: 'Leh to Nubra Valley',
        description: 'Drive via Khardungla Pass. Visit Diskit Monastery and Hunder sand dunes.',
        activities: ['Khardungla Pass', 'Monastery Visit', 'Camel Ride'],
      },
      {
        day: 4,
        title: 'Nubra to Pangong',
        description: 'Drive to Pangong Lake via Shyok river route. Evening at the lake.',
        activities: ['Scenic Drive', 'Lake Visit', 'Photography'],
      },
      {
        day: 5,
        title: 'Pangong to Leh',
        description: 'Morning at Pangong Lake. Drive back to Leh via Changla Pass.',
        activities: ['Lake Sunrise', 'Changla Pass', 'Return Journey'],
      },
      {
        day: 6,
        title: 'Leh to Kargil',
        description: 'Drive to Kargil via Magnetic Hill and Gurudwara Pathar Sahib.',
        activities: ['Magnetic Hill', 'Gurudwara Visit', 'Scenic Drive'],
      },
      {
        day: 7,
        title: 'Departure',
        description: 'Transfer to Leh airport for departure.',
        activities: ['Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '6 nights accommodation',
      'Private vehicle',
      'Breakfast',
      'Inner line permits',
      'Driver allowance',
    ],
    excluded: [
      'Flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner',
      'Tips',
    ],
  },
  {
    id: 5,
    slug: 'santorini-sunsets',
    title: 'Santorini Sunsets',
    short_description: 'Romantic sunsets & white-washed Greek beauty',
    image_url:
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=900&q=80',
    tour_type: 'international',
    description: 'Romantic getaway to the most beautiful island in Greece with stunning sunsets and white-washed buildings.',
    price: 145000,
    duration: '5 Days',
    best_time_to_visit: 'April to October',
    popular_places: [
      {
        name: 'Oia',
        location: 'Santorini',
        image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Fira',
        location: 'Santorini',
        image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Red Beach',
        location: 'Santorini',
        image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Santorini',
        description: 'Arrive at Santorini airport. Transfer to hotel in Oia. Evening sunset viewing.',
        activities: ['Airport Transfer', 'Hotel Check-in', 'Sunset View'],
      },
      {
        day: 2,
        title: 'Oia Exploration',
        description: 'Explore Oia village, visit Amoudi Bay, and enjoy local cuisine.',
        activities: ['Village Walk', 'Bay Visit', 'Local Dining'],
      },
      {
        day: 3,
        title: 'Fira and Caldera Cruise',
        description: 'Visit Fira town. Afternoon caldera cruise with volcano visit.',
        activities: ['Town Visit', 'Boat Cruise', 'Volcano Tour'],
      },
      {
        day: 4,
        title: 'Beach Day',
        description: 'Visit Red Beach, Perissa Beach, and Akrotiri archaeological site.',
        activities: ['Beach Visit', 'Archaeological Site', 'Swimming'],
      },
      {
        day: 5,
        title: 'Departure',
        description: 'Morning at leisure. Transfer to airport for departure.',
        activities: ['Shopping', 'Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '4 nights accommodation',
      'Daily breakfast',
      'Airport transfers',
      'Caldera cruise',
      'Volcano tour',
    ],
    excluded: [
      'International flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner',
      'Tips',
    ],
  },
  {
    id: 6,
    slug: 'rajasthan-royal-trail',
    title: 'Rajasthan Royal Trail',
    short_description: 'Forts, palaces & royal heritage experience',
    image_url:
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80',
    tour_type: 'domestic',
    description: 'Experience the royal heritage of Rajasthan with magnificent forts, palaces, and vibrant culture.',
    price: 65000,
    duration: '6 Days',
    best_time_to_visit: 'October to March',
    popular_places: [
      {
        name: 'Jaipur',
        location: 'Rajasthan',
        image_url: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Jodhpur',
        location: 'Rajasthan',
        image_url: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Udaipur',
        location: 'Rajasthan',
        image_url: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Jaipur',
        description: 'Arrive at Jaipur airport. Transfer to hotel. Evening visit to Hawa Mahal.',
        activities: ['Airport Transfer', 'Hawa Mahal Visit', 'Market Walk'],
      },
      {
        day: 2,
        title: 'Jaipur Sightseeing',
        description: 'Visit Amber Fort, City Palace, Jantar Mantar, and local bazaars.',
        activities: ['Fort Visit', 'Palace Tour', 'Market Shopping'],
      },
      {
        day: 3,
        title: 'Jaipur to Jodhpur',
        description: 'Drive to Jodhpur. Visit Mehrangarh Fort and Jaswant Thada.',
        activities: ['Scenic Drive', 'Fort Visit', 'Memorial Visit'],
      },
      {
        day: 4,
        title: 'Jodhpur to Udaipur',
        description: 'Drive to Udaipur via Ranakpur Jain Temple. Evening Lake Pichola boat ride.',
        activities: ['Temple Visit', 'Boat Ride', 'Hotel Check-in'],
      },
      {
        day: 5,
        title: 'Udaipur Sightseeing',
        description: 'Visit City Palace, Saheliyon ki Bari, and Jagdish Temple.',
        activities: ['Palace Visit', 'Garden Tour', 'Temple Visit'],
      },
      {
        day: 6,
        title: 'Departure',
        description: 'Transfer to Udaipur airport for departure.',
        activities: ['Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '5 nights accommodation',
      'Private vehicle',
      'Breakfast',
      'Monument entrance fees',
      'Boat ride',
    ],
    excluded: [
      'Flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner',
      'Tips',
    ],
  },
  {
    id: 7,
    slug: 'dubai-desert-luxe',
    title: 'Dubai Desert Luxe',
    short_description: 'Modern luxury meets desert adventure',
    image_url:
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=900&q=80',
    tour_type: 'international',
    description: 'Experience the perfect blend of modern luxury and desert adventure in Dubai.',
    price: 75000,
    duration: '4 Days',
    best_time_to_visit: 'November to April',
    popular_places: [
      {
        name: 'Burj Khalifa',
        location: 'Downtown Dubai',
        image_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Desert Safari',
        location: 'Dubai Desert',
        image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Palm Jumeirah',
        location: 'Dubai Coast',
        image_url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Dubai',
        description: 'Arrive at Dubai airport. Transfer to hotel. Evening Dubai Marina walk.',
        activities: ['Airport Transfer', 'Marina Walk', 'Dinner Cruise'],
      },
      {
        day: 2,
        title: 'Dubai City Tour',
        description: 'Visit Burj Khalifa, Dubai Mall, and Old Dubai souks.',
        activities: ['Burj Khalifa', 'Dubai Mall', 'Souk Visit'],
      },
      {
        day: 3,
        title: 'Desert Safari',
        description: 'Morning desert safari with dune bashing, camel ride, and BBQ dinner.',
        activities: ['Dune Bashing', 'Camel Ride', 'BBQ Dinner'],
      },
      {
        day: 4,
        title: 'Departure',
        description: 'Morning at leisure. Transfer to airport for departure.',
        activities: ['Shopping', 'Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '3 nights accommodation',
      'Daily breakfast',
      'Airport transfers',
      'Desert safari',
      'Burj Khalifa tickets',
    ],
    excluded: [
      'International flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner',
      'Tips',
    ],
  },
  {
    id: 8,
    slug: 'goa-coastal-break',
    title: 'Goa Coastal Break',
    short_description: 'Beaches, Portuguese heritage & vibrant nightlife',
    image_url:
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80',
    tour_type: 'domestic',
    description: 'Relax on pristine beaches, explore Portuguese heritage, and experience vibrant nightlife in Goa.',
    price: 35000,
    duration: '4 Days',
    best_time_to_visit: 'November to February',
    popular_places: [
      {
        name: 'Baga Beach',
        location: 'North Goa',
        image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Old Goa',
        location: 'Central Goa',
        image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80',
      },
      {
        name: 'Palolem Beach',
        location: 'South Goa',
        image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=900&q=80',
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Goa',
        description: 'Arrive at Goa airport. Transfer to hotel in North Goa. Evening beach time.',
        activities: ['Airport Transfer', 'Hotel Check-in', 'Beach Walk'],
      },
      {
        day: 2,
        title: 'North Goa Exploration',
        description: 'Visit Baga Beach, Calangute, and Anjuna. Evening at a beach club.',
        activities: ['Beach Hopping', 'Water Sports', 'Nightlife'],
      },
      {
        day: 3,
        title: 'South Goa and Old Goa',
        description: 'Visit Old Goa churches, Panjim city, and Palolem Beach.',
        activities: ['Church Visit', 'City Tour', 'Beach Visit'],
      },
      {
        day: 4,
        title: 'Departure',
        description: 'Morning at leisure. Transfer to airport for departure.',
        activities: ['Shopping', 'Airport Transfer', 'Departure'],
      },
    ],
    included: [
      '3 nights accommodation',
      'Daily breakfast',
      'Airport transfers',
      'Sightseeing',
    ],
    excluded: [
      'Flights',
      'Travel insurance',
      'Personal expenses',
      'Lunch and dinner',
      'Tips',
    ],
  },
];
